FROM php:7.2.11-apache

LABEL \
    version="1.0" \
    this.docker.file.author="Pluto Solutions <kajornjit@gmail.com>" \
    links.github="https://github.com/plutosolutions" \
    description="Pluto Solutions Development"

RUN apt-get update && \
    apt-get clean
